spring:
  application:
    name: library-management-system

  datasource:
    url: "jdbc:mysql://localhost:3306/lms-database?allowPublicKeyRetrieval=true"
    username: "lms-user"
    password: "lmsPassword"
    hikari:
      schema: lms-database

  jpa:
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration

server:
  port: 8080

logging:
  level:
    root: info
    org.springframework: error
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %level [%thread] [%file:%line] %msg%n"

